### ISSUE TITLE
RTCPeerConnection exception in chrome

### ISSUE THREAD

**Issue by jonathanherr** [balena-io-playground/balena-cam#23]
Received this exception in chrome 66.0.3359.181 on Ubuntu 16.04

client.js:56 Uncaught TypeError: pc.addTransceiver is not a function
    at negotiate (client.js:56)
    at client.js:156

Which is maybe consistent with this page on RTCPeerConnection from MDN?
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTransceiver

**Comment by mbalamat** [comment]
Hi @jonathanherr thanks for trying balena-cam and pointing this out!
The MDN browser compatibility table has to change for this one.
Have you tried updating chrome? The latest version I think is around 71.
